version: '3'
networks:
  brasil-swing-network:
    driver: bridge
services:
  brasil-swing-db:
    image: mongo:4.2
    hostname: brasil-swing-db
    container_name: brasil-swing-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: brasilswing
      MONGO_INITDB_DATABASE: brasilswing
    ports:
      - 27017:27017
    networks:
      - brasil-swing-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api-brasil-swing
    container_name: api-brasil-swing
    environment:
      PORT: 3000
      MEMORY: 1024
      DATABASE_URI: mongodb://root:brasilswing@brasil-swing-db:27017/brasilswing?authSource=admin
    depends_on:
      - brasil-swing-db
    links:
      - brasil-swing-db
    ports:
      - 3000:3000
    networks:
      - brasil-swing-network

